name: 'talent_match_intel'
version: '1.0.0'
config-version: 2

# Harus SAMA persis dengan key di profiles.yml di atas
profile: 'talent_match_intel'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets: ['target', 'dbt_packages']

vars:
  perf_year: 2024
  high_rating: 5


models:
  talent_match_intel:
    +materialized: view
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    marts:
      +schema: marts

models:
  - name: int_competencies_imputed
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [employee_id, pillar_code, year]
    columns:
      - name: score_imputed
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 5
              inclusive: true

version: 2
models:
  - name: int_performance_imputed
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [employee_id, year]
    columns:
      - name: rating_imputed
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 5
              inclusive: true

version: 2
models:
  - name: int_papi_imputed
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [employee_id, scale_code]
    columns:
      - name: score_imputed
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 9
              inclusive: true


models:
  - name: stg_tgv_features
    description: "Latest per-employee features: cognitive_norm, competency_norm, performance_norm"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [employee_id]
    columns:
      - name: cognitive_norm
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true
      - name: competency_norm
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true
      - name: performance_norm
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true