version: 2

models:
  - name: stg_employees
    description: "Employees (cleaned & typed) dari raw.employees"
    columns:
      - name: employee_id
        tests:
          - not_null
          - unique
      - name: years_of_service_months
        description: "Masa kerja (bulan)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

  - name: stg_performance_yearly
    description: "Annual performance ratings (1–5)"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [employee_id, year]
    columns:
      - name: employee_id
        tests: [not_null]
      - name: year
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 2021
              max_value: 2025
              inclusive: true
      - name: rating
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 5
              inclusive: true

  - name: stg_papi_scores
    description: "PAPI Kostick scale scores 1–9"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [employee_id, scale_code]
    columns:
      - name: employee_id
        tests: [not_null]
      - name: scale_code
        tests: [not_null]
      - name: score
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 9
              inclusive: true

  - name: stg_strengths
    description: "CliftonStrengths top ranks (1–14 unik per employee)"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [employee_id, rank]
    columns:
      - name: employee_id
        tests: [not_null]
      - name: rank
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 14
              inclusive: true

  - name: stg_competencies_yearly_clean
    description: "Historical competency pillars (scores 1–5, year 2021–2025, pillar valid)"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [employee_id, pillar_code, year]
    columns:
      - name: employee_id
        tests: [not_null]
      - name: pillar_code
        tests:
          - not_null
          - relationships:
              to: source('raw','dim_competency_pillars')
              field: pillar_code
      - name: year
        tests:
          - dbt_utils.accepted_range:
              min_value: 2021
              max_value: 2025
              inclusive: true
      - name: score
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 5
              inclusive: true
